language: python
python: "3.5"
addons:
    apt:
        packages:
            - libsdl2-dev
            - libsdl2-ttf-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libgstreamer1.0-dev
            - gstreamer1.0-alsa
            - gstreamer1.0-plugins-base
            - python-dev
            - libsmpeg-dev
            - libswscale-dev
            - libavformat-dev
            - libavcodec-dev
            - libjpeg-dev
            - libtiff4-dev
            - libX11-dev
            - libmtdev-dev
            - libgl1-mesa-dev
            - libgles2-mesa-dev
            - xvfb
            - pulseaudio
install:
    - pip install -U pip setuptools wheel
    - pip install -U Cython==0.21.2
    - pip install -r requirements-test.txt
    - pip install -e .
before_script:
    export DISPLAY=:99.0;
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
script:
    - py.test --cov-config .coveragerc --cov=vidhubcontrol
after_success:
    - coveralls
