language: python
python: "3.5"
addons:
    apt:
        sources:
            - sourceline: 'ppa:kivy-team/kivy-daily'
        packages:
            - kivy
install:
    - pip install -U pip setuptools wheel
    - pip install -r requirements-test.txt
    - pip install -e .
script:
    - py.test --cov-config .coveragerc --cov=vidhubcontrol
after_success:
    - coveralls
