dist: trusty
sudo: false
language: python
matrix:
    include:
    - python: "3.5"
      env:
          - ALLOW_DEPLOY=false
    - python: "3.6"
      env:
          - ALLOW_DEPLOY=true
cache:
    directories:
        - "build/"
addons:
    apt:
        packages:
            - libsdl2-dev
            - libsdl2-ttf-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libgstreamer1.0-dev
            - gstreamer1.0-alsa
            - gstreamer1.0-plugins-base
            - python-dev
            - libsmpeg-dev
            - libswscale-dev
            - libavformat-dev
            - libavcodec-dev
            - libjpeg-dev
            - libtiff4-dev
            - libx11-dev
            - libmtdev-dev
            - libgl1-mesa-dev
            - libgles2-mesa-dev
            - xvfb
            - pulseaudio
            - xclip
install:
    - ./tools/install-deps.sh
    - pip install -r doc/requirements.txt
    - pip install -e .
script:
    - travis-sphinx build --source=doc/source --nowarn
    - ./runtests.sh
after_success:
    - coveralls
    - sh -c "if [ '$ALLOW_DEPLOY' = 'true' ]; then travis-sphinx deploy; fi"
deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    on:
        python: "3.6"
        tags: true
    user: nocarryr
    password:
      secure: Tf3btFV2NLkRvN85t/9xFWsIFZok3QeFXTbT/2RKK6n8aRSScuObyzC7Tg7l/xJyZVy4m7Cc6gibUtr33wU/b5OVK+ifDoNu0S6SzezFTWnx5yDfnJC6BVX3UYK1efua0P/YPlnQowRMNP3acAcXLzr85x7GRkfJHFVSGBUW9rbX+abYcu61nZBXrLVEwOWDfnaTwpqbLD6hiHCEovQEbXFHB4DZ8irWgLLEF/KVOfZFF0byJcLgYD9Pk+M3CNNoq5kocBHf1X9/Vymu2IeLIaFzyAbBJ6xD9IOZIFuBEX/fn/iOVwysc4WTHzFiZ31/uGFBtVbHMNzKYhhx5KMHBlLT/j6ovlvxdgEy0icp7CVqmLqnzg5OBTTq86PN0V6nwEnfgdRzyL+2wDIY9pc7fSsz8GTcOpXzFocGovGIg4nrbdT3rnrDXsi2GN4OmN3HrPfIHoE2Yq/uMJf6D6msPIiaeh7ph6WN/A8jz3jN4r5/ko9mZar/koek+yWRT1i1Tsz3ySXdcIRyc4QGIxwTzlSWs4fPIjNDMve8+s7T37paYTiVlYx6T6TPK/gd5ITwA1kDRtzkdePbSSN9t83MvEXXD/RMdSS5dpykh+u3J8DaEXp5wPL5yphLX1pkePtPVSWX3/4xbAIEXuigk93Tk/oyW5EQOKZ3c0K8kHoEZ8o=
